version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing npm...
      - npm install
  build:
    commands:
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 574868243623.dkr.ecr.eu-west-1.amazonaws.com
      - docker build -t nodejs-image-repository ./myApp/
      - docker tag nodejs-image-repository:latest 574868243623.dkr.ecr.eu-west-1.amazonaws.com/nodejs-image-repository:latest
      - docker push 574868243623.dkr.ecr.eu-west-1.amazonaws.com/nodejs-image-repository:latest
      - echo Build started on `date`
      - echo Compiling the Node.js code

# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
