version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing npm...
      - npm install
  build:
    commands:
      - docker build -t my-nodejs-image ./myApp/
      - echo Build started on `date`
      - echo Compiling the Node.js code

# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
