apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app
  name: nodejs-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
  spec:
      containers:
        - name: status
          image: 574868243623.dkr.ecr.eu-west-1.amazonaws.com/nodejs-image-repository:latest
          ports:
            - containerPort: 8080